# Generated by Django 4.2.2 on 2023-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
